version: "2"

services:
  # wifi-connect:
  #   image: bh.cr/balenalabs/wifi-connect-aarch64
  #   restart: always
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: "1"
  #     io.balena.features.firmware: "1"

  node-player:
    image: lucassaid/ritmo-node-player
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
      - /usr/local/bin/ritmo/db:/usr/local/bin/ritmo/db
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      API_URL: https://staging-api.ritmostudio.com
      JWT_SECRET: 2d019272a5871508437fbecde397fd79e32d8c35cd9ce4815fcd5a7b466bd8b7
      NODE_ENV: staging

  control-ui:
    image: lucassaid/ritmo-box-ui
    restart: on-failure
    ports:
      - "80:3000"
    depends_on:
      - node-player

  # supervisor-proxy:
  #   build: ./supervisor-proxy
  #   restart: on-failure
  #   ports:
  #     - "8083:8083"
  #   depends_on:
  #     - control-ui
  #   environment:
  #     JWT_SECRET: 2d019272a5871508437fbecde397fd79e32d8c35cd9ce4815fcd5a7b466bd8b7
  #   labels:
  #     io.balena.features.supervisor-api: '1'
