version: "2"

volumes:
  pulse:

services:
  audio:
    image: lucassaid/ritmo-audio
    privileged: true
    volumes:
      - "pulse:/run/pulse"

  node-player:
    depends_on:
      - audio
    image: lucassaid/ritmo-node-player
    volumes:
      - "pulse:/run/pulse"
      - /usr/local/bin/ritmo/db:/usr/local/bin/ritmo/db
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      API_URL: https://api.ritmostudio.com
      JWT_SECRET: 2d019272a5871508437fbecde397fd79e32d8c35cd9ce4815fcd5a7b466bd8b7
      NODE_ENV: production

  control-ui:
    image: lucassaid/ritmo-box-ui
    restart: on-failure
    ports:
      - "80:3000"
    depends_on:
      - node-player
